# Generated by Django 4.2.2 on 2023-07-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('hit_die', models.CharField(choices=[('d6', 'D6'), ('d8', 'D8'), ('d10', 'D10'), ('d12', 'D12')], max_length=3)),
                ('primary_ability', models.CharField(max_length=128)),
            ],
        ),
    ]
