# Generated by Django 4.2.2 on 2023-07-02 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classes',
            table='classes',
        ),
    ]
